In [24]:
# importing the module 
import numpy as np
from numpy import linalg as LA
  
# creating two matrices 
A = np.array([[1/2, 1/2],[1/2, 1/2]])
B = np.array([[1, 0], [0, -1]])
C = np.dot(A,B)
print(C)

[[ 0.5 -0.5]
 [ 0.5 -0.5]]


In [29]:
print(LA.matrix_power(A, 37))
print(LA.matrix_power(B, 63))
print(LA.matrix_power(B, 138))
print(LA.matrix_power(C, 42))

[[0.5 0.5]
 [0.5 0.5]]
[[ 1  0]
 [ 0 -1]]
[[1 0]
 [0 1]]
[[0. 0.]
 [0. 0.]]


Question 2:

In [32]:
I = np.identity(2)
neg_I = -I
print(neg_I)

[[-1. -0.]
 [-0. -1.]]


Question 3:

In [50]:
#define initial guesses:
x0 = 20
y0 = 20
z0 = 1

# Setting error to move into the while loop
error=20

# Setting up iteration counter
count=0

while error>1.E-6:
    count+=1
    x = (800-3*y0+2*z0)/100
    y = (1000-x0-5*z0)/200
    z = (500 + 4*x0 - 3*y0)/100

    error = abs(x-x0)+abs(y-y0)+abs(z-z0)

    x0 = x
    y0 = y
    z0 = z
print(x, y, z)
    

7.95854215137929 4.830871902943531 5.17341552630798


Question 4:
